<a href="https://colab.research.google.com/github/subodh2708/deep-learning---tensorflow-2.0/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# we are going to cover some fundamental concepts of tensor in tensorflow

## introduction to tensors

In [73]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [74]:
# create tensor
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [75]:
# check number of dimension of tensor

scaler.ndim

0

In [76]:
# create vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [77]:
vector.ndim

1

In [78]:
# create a matrix

matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [79]:
# create another matrix

another_matrix = tf.constant([[1,2],
                              [3,4],
                              [5,6]],dtype = tf.float16)

In [80]:
another_matrix.ndim

2

In [81]:
# create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [82]:
tensor.ndim

3

In [83]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [87]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [88]:
# create two random(but the same) tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [89]:
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [6,7]])
not_shuffled.ndim

2

In [90]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [6, 7]], dtype=int32)>

other ways to make tensors

In [91]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [92]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## turn numpy into tensors

In [93]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [94]:
A = tf.constant(numpy_A,shape = (2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [95]:
A.ndim, B.ndim

(3, 1)

In [96]:
# Create rank 4 tensor(4 dimension)

rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [97]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor), rank_4_tensor.dtype

(4,
 TensorShape([2, 3, 4, 5]),
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32)

In [98]:
rank_4_tensor.shape[-1]

5

# indexing tensors

In [99]:
# first two element of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [100]:
# Create rank 2 tensor

In [101]:
rank_2_tensor = tf.constant(np.random.randint(2,10,(2,3)))

In [102]:
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[9, 5, 2],
       [6, 3, 4]])>

In [103]:
rank_2_tensor[1,-2]

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [104]:
# add extra dimension to rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]

# alternative

tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 3, 1), dtype=int64, numpy=
array([[[9],
        [5],
        [2]],

       [[6],
        [3],
        [4]]])>

In [105]:
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int64, numpy=
array([[[9],
        [5],
        [2]],

       [[6],
        [3],
        [4]]])>

# manipulating tensors ( tensor operations)

In [106]:
# addition 

tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [107]:
 # we can use tensorflow  built-in function for operation
 tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# matrix multiplication

In [108]:
tensor_1 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])

In [109]:
tensor_1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [110]:
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])
tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [111]:
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [112]:
a = tf.constant([[1,2],[3,4],[5,6]])

In [113]:
b = tf.constant([[7,8],[9,10],[11,12]])

In [114]:
# let's change the shape of b

tf.matmul(a,tf.reshape(b,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [115]:
a.shape, b.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [116]:
tf.matmul(tf.reshape(a,(2,3)), b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [117]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

# Changing datatype of a tensor

In [118]:
A = tf.constant([1,2,3])

In [119]:
A.dtype

tf.int32

In [122]:
B = tf.cast(A,dtype=tf.float16)

In [123]:
B.dtype, B

(tf.float16,
 <tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>)

# Aggregating tensors

In [124]:
E = tf.constant(np.random.randint(0,100,size=50))

In [125]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13, 78, 53, 99, 58, 51, 57, 56, 27, 45, 53, 49,  0, 76, 94, 42, 17,
       53, 62, 47, 63, 82,  0, 67, 29, 18, 63, 25, 79, 13, 50,  5, 44, 29,
       23, 59, 56, 47, 72, 89,  1, 51, 85, 45, 82, 26, 43, 35, 72, 89])>

In [126]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [128]:
tf.reduce_max(E) , tf.reduce_min(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2472>)

In [129]:
import tensorflow_probability as tfp

In [131]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=660>

In [135]:
tf.math.reduce_variance(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=660.6464>

In [133]:
tf.math.reduce_std(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.703043>

In [137]:
# find the positional maximum and mininum

tf.random.set_seed(42)
F = tf.random.uniform([50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [142]:
tf.argmax(F)
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [141]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing the tensors ( removing all the single dimensions)

In [149]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [152]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape,G_squeezed.ndim, tf.size(G_squeezed)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

## one hot encoding tensors

In [153]:
list_1  = [0,1,2,3]

In [160]:
tf.one_hot(list_1, depth= 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [162]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [163]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [165]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [168]:
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# finding Access to GPU

In [2]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Sat Aug  6 15:05:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------